# void-space color scheme for Kitty
# https://sw.kovidgoyal.net/kitty/conf/#color-scheme

# Background and foreground
background              #1a1f28
foreground              #99a7be

# Selection
selection_background    #323c4d
selection_foreground    #99a7be

# Cursor
cursor                  #99a7be
cursor_text_color       #1a1f28

# URL underline color
url_color               #4ab5c4

# Normal colors
color0  #1a1f28
color1  #c68b8f
color2  #8fb98c
color3  #b39b64
color4  #618bc2
color5  #9b88d0
color6  #4ab5c4
color7  #323c4d

# Bright colors
color8   #232936
color9   #ba8873
color10  #8fb98c
color11  #d5ad75
color12  #618bc2
color13  #cc7dd0
color14  #5f7090
color15  #99a7be
